#!/bin/sh

#PBS -l walltime=48:00:00
#PBS -l nodes=1:mars.ihs.uni-stuttgart.de:ppn=8


# go to submit directory
cd $PBS_O_WORKDIR


# load OpenFOAM000
#module load cae/openfoam/v2206
#source $FOAM_INIT
#. openfoam of_v2406_15.6
#. dtoo of_v2406_15.6
source /mnt/scratch/rraj/venvs/py311/bin/activate

export OSLO_LOCK_PATH=~/tmp


export FOAM_SIGFPE=false

python train_gan.py train 3 10 > output_3_10.log

touch training_3_10.finished

deactivate
